site_name: tumblr-backup
site_url: https://cebtenzzre.github.io/tumblr-utils
repo_url: https://github.com/cebtenzzre/tumblr-utils
repo_name: cebtenzzre/tumblr-utils

theme:
  name: material

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

nav:
  - Home: index.md
  - Installation: installation.md
  - Getting Cookies: cookies.md
  - Usage: usage.md
  - How It Works: operation.md
